### ISSUE TITLE
cannot open shader files (bad project structure)

### ISSUE THREAD

**Issue by Tokusei** [JoeyDeVries/LearnOpenGL#146]
Hello, I am using VS2019.  I generated the libs/headers for my specific platform, Then referenced them in CMake so the project would target them (that didnt work, and I had to replace the default libs/headers which came with the repo and generate a default config)

The problem is that when opening some of the projects (such as 1.getting_started_4.2.textures_combined) some of the source code cannot reference the correct directory.

a key example is the following:

`textures_combined.cpp
52     Shader ourShader("4.2.texture.vs", "4.2.texture.fs");
`
tries to build the shader program by passing two shader files relative to the source directory

`..\src\1.getting_started\4.2.textures_combined\textures_combined.cpp
..\src\1.getting_started\4.2.textures_combined\4.2.texture.vs`

however the header which executes ourShader(); is in a different directory

`\includes\learnopengl\shader.h`

it is trying to find the vs/fs files in this directory, but they are in the source directory. does this mean the project is misconfigured, or have I made a mistake?

**Comment by JoeyDeVries** [comment]
The header is indeed in a different directory, but because the header is included in the `textures_combined.cpp` file it's part of `textures_combined.cpp` when compiled, so it should follow the directory of whatever project settings that cpp file is defined in. I'm not sure what happens here exactly (especially since you mention that it happens on 'some' of the projects), but it does look like something went wrong on the CMake side if it can't find the shader in that project.

**Comment by Tokusei** [comment]
Ah, I see what you mean. The include will be added to the cpp on compile time so the paths will be the same.
I have checked the directories. When I debug the project, a binary is generated and executed at the following directory
`..\bin\1.getting__started\Debug\1.getting_started_4.1.textures.exe`

however when running a function to return the current working directory on runtime, it returns the following
`current path is "D:\\repos\\LearnOpenGL\\built`

Is there some way I can point the CWD to the same directory as the binaries? because in the binary directory there are copies of all the shaders from each class so it can be easily loaded

**Comment by JoeyDeVries** [comment]
It's been a while though so not 100% sure anymore, but the executable that runs (when you hit run/debug on visual studio; F5) checks for shaders in the directory of the executable at that point (the way it's set up). This also explains why it works if you copy over the shaders manually.

What we've done for Visual Studio is add a pre-compile hook that copies over the shaders in the same project to the build directoy of that executable so that when you build, the shaders are indeed there (so automating the step you did manually). This only happens on compile though so if you make changes to the local shader you'd have to hit re-compile to make sure the versions in the build folder are updated as well.

**Comment by JoeyDeVries** [comment]
If this doesn't work anymore on VS 2019 I'll have to see if I can fix that. I'll see if I can reserve some time to pick this up next week.

**Comment by Tokusei** [comment]
Yes, The shaders are in the same directory as the binary. When I debug the program it spawns the binary in `..\bin\1.getting_started\Debug` which also has a copy of all the shaders for the first section

the issue is that the application has its CWD set to something other than the path of the executable. so when ifstream tries to open the shader it's looking in `..\built`

If I inspect the VS project properties (Configuration Properties -> Debugging) it shows that the Working Directory path is set to `$(ProjectDir)` which is why it looks at `..\built` I could manually change the path, but as each section has it's down directory in \bin it requires a lot of clicking. Maybe this is a new flag in VS which sets the CWD to something other than where the binary is written?

**Comment by MaoKwen** [comment]
Add this line to CMakeLists.txt works fine for me.
```cmake
set_target_properties(${NAME} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/bin/${CHAPTER}/Debug")
```

**Comment by JoeyDeVries** [comment]
I've just pushed a fix with @MaoKwen 's statement (thanks!) and debugging in VS works again.
