### ISSUE TITLE
Calculation of NormalMatrix

### ISSUE THREAD

**Issue by vexe** [JoeyDeVries/LearnOpenGL#20]
Hi there,

not an issue but more of a question: in your normal mapping tutorial code https://github.com/JoeyDeVries/LearnOpenGL/blob/master/src/5.advanced_lighting/4.normal_mapping/normal_mapping.vs

shouldn't the NormalMatrix be computed by transpose(inverse(ModelToViewMatrix)) (which is WorldToView * ModelToWorld) instead of the ModelToWorld matrix like you have it in the code? (at least from what I've read from other sources)

My guess is that they're both correct. Depending on which space we want our calculations to be in, which in the case of your tutorial you have the LightPos, ViewPos in world space  - not eye/camera space - so you construct the normal matrix using the 'model' (ModelToWorld) matrix, is that correct?

**Comment by JoeyDeVries** [comment]
Yes. In (all) of my tutorials I calculate lighting in world space instead of view space that you commonly see in online resources. One isn't necessarily better than the other, it's just that I found world space more intuitive when explaining lighting than view space when I first introduced it and it sort of sticked.

Because I do the transformations in world space and not in view space I also keep the normal matrix in world space and thus skip the 'WorldToView' step so that everything stays in the same coordinate space. Of course if you want everything done in view/eye space you'd also want to have the normal matrix in view space. 

I hope I understood you correctly and this answers your question :)

**Comment by vexe** [comment]
Thanks yeah that made sense. Great tutorials btw! I've been reading other opengl books but most the times I come to find that your explanations on the same topics are always better.

One more question if you don't mind: regarding the Normal Matrix, why do we need it? I mean we get the VertexNormal in object/local space, if we want that in world space why not just multiply it directly with ModelToWorld? why does it have to be transpose(inverse(ModelToWorld))? 

And about the construction of TBN from the NormalMatrix, just to make sure I understand the various ways to construct it, are these three lines correct?

    TBN_ToLocal = mat3(Tangent_Local, Bitangent_Local, Normal_Local); // converts from tangent to local/object space - take the transpose to go the other way around. Normal_Local etc are what is fed to our vertex shader via our slots (location = 0, etc)
    TBN_ToWorld = mat3(Tangent_World, Bitangent_World, Normal_World); // converts from tangent to world space
    TBN_ToCamera = mat3(Tangent_Camera, Bitangent_Camera, Normal_Camera); // converts from tangent to camera space

Also, before I do the cross product between Tangent and Normal to get Bitangent, I would have to do the Gram-Schmidt on T and N to make sure they're orthogonality first right? In the tutorial's code you did it on the transformed Tangent and Normal to get the transformed Bitangent, I guess this is more efficient than if you were to do Gram-schmidt on the non-transformed Tangent/Normal and then transform the three together, am I correct? i.e.

    VertexTangent = normalize(VertexTangent - dot(VertexTangent, VertexNormal) * VertexNormal);
    vec3 Bitangent = cross(VertexTangent, VertexNormal);
    mat3 NormalMatrix = transpose(inverse(mat3(ModelToWorld)));
    vec3 T = NormalMatrix * VertexTangent;
    vec3 B = NormalMatrix * Bitangent;
    vec3 N = NormalMatrix * VertexNormal;
    mat3 TBN = transpose(mat3(T, B, N));

**Comment by vexe** [comment]
Never mind about VertexTangent = normalize(...) "Error can't modify input" :D

**Comment by JoeyDeVries** [comment]
Using a normal matrix makes sure normals stay properly aligned to a surface when doing non-uniform scaling. Most people don't use it as doing non-uniform scaling isn't that common.
If you want to know more check out the 'One last thing' section of the http://learnopengl.com/#!Lighting/Basic-Lighting tutorial.

However, if I think about it, it's probably only necessary for the normal vector as I don't think the tangent and bitangent can be negatively influenced by non-uniform scaling, in which case the normalmatrix isn't necessary (it is for the normal when doing non-uniform scaling). I'll have to check this and potentially update the tutorial if necessary as it would then only complicate things.

And yes, doing the Gram-Schmidth in a later stage is more efficient as this saves you a matrix multiplication.

**Comment by vexe** [comment]
So if I'm not using non-uniform scaling, I would build the TBN directly without the need of a NormalMatrix?

**Comment by JoeyDeVries** [comment]
That should work yes, the normalMatrix is just there to ensure that whatever model transform you do, it won't incorrectly transform the normals.

**Comment by vexe** [comment]
Instead of doing it in the vertex shader, what do you think about doing the gram-schmidt on the T N in our obj loader when reading in the normals and computing T and B?

**Comment by JoeyDeVries** [comment]
It's there because (most) model loaders that calculate tangents also average the tangent vectors based on the surrounding triangle primitives so in that case you'll quite often get a tangent that isn't completely orthogonal. I'm not sure if you could do this in an obj loader as vertices are often shared by multiple triangles, in which case it's difficult or impossible to define an orthogonal tangent for this vertex. I'm not 100% sure, but I think that's the case.

Also, if you were to send the TBN vectors to the fragment shader and construct the TBN matrix in the fragment shader, the vectors could also become non-orthogonal due to fragment interpolation in which case you'd want to do the gram-schmidt process in the fragment shader.
