### ISSUE TITLE
Provide which version of MSVC the windows lib are compatible with

### ISSUE THREAD

**Issue by jokoon** [JoeyDeVries/LearnOpenGL#22]
The cmake script doesn't work out of the box, I get linking errors, it's probably because I have MSVC 11 (2012), I don't know if I should use 2013 or 2015.

Can't cmake detect that or have a way to select a folder containing the proper lib files according to this?

**Comment by JoeyDeVries** [comment]
The provided libraries are built against the MSVC compiler (not exactly sure which version it was) so if you get linking errors this is likely because the library built isn't compatible with your compiler (or newer versions of MSVC). 
In that case I recommend checking your linking errors which library is causing the conflicts and build that library yourself given your compiler.

As to if CMake can't do this automatically, I'm not sure as I'm a complete beginner when it comes to CMake. If I recall correctly, Polytonic/Glitter from @Polytonic did something similar I believe by externally including the repositories of the required libraries so these are compiled on demand as well.

**Comment by Polytonic** [comment]
> The cmake script doesn't work out of the box, I get linking errors, it's probably because I have MSVC 11 (2012), I don't know if I should use 2013 or 2015.

Which library (or libraries) fail to link properly? You may need to provide an older set of .lib/.dll files for MSVC 11, or upgrade toolchains. 

> As to if CMake can't do this automatically, I'm not sure as I'm a complete beginner when it comes to CMake. If I recall correctly, Polytonic/Glitter from @Polytonic did something similar I believe by externally including the repositories of the required libraries so these are compiled on demand as well.

Glitter compiles and links static versions of each library to get around the version mismatch problem.

**Comment by jokoon** [comment]
> Which library (or libraries) fail to link properly?

Mostly glfw. I put another version I got from their website, but I still had include and header errors.

I'm going to try with MSVC 2015.

**Comment by jokoon** [comment]
Okay, so when using MSVC 2013, and configuring the project with cmake, and choosing standard MSVC 2013, not win64, it worked.

Took me some time since I had not all MSVC version and not sure if 32/64 could cause a problem.
