### ISSUE TITLE
Ad is in an annoying place

### ISSUE THREAD

**Issue by ArcE404** [JoeyDeVries/LearnOpenGL#375]
![image](https://github.com/JoeyDeVries/LearnOpenGL/assets/82833443/d4dff9bb-a456-4f2a-9e62-31392cf78757)
This Ad appears on the introduction page and makes it difficult to navigate through the page.
![image](https://github.com/JoeyDeVries/LearnOpenGL/assets/82833443/5579ae0e-0edc-462d-867d-879796ee8f6e)

**Comment by JoeyDeVries** [comment]
Shit, this is definitely not the right behavior, sorry! Second time I've been hearing of this and thought it was fixed.

Do you have some extra info for me to see if I can try and reproduce?
- What OS/Browser are you using?
- Screen/window size browser window?
- On desktop or mobile?
- What country are you visiting website from? (If you want to share, otherwise ignore)

Thanks!

**Comment by ArcE404** [comment]
Sure thing:
I'm using chrome on a Windows 10 computer (desktop), it appears in a full-size window on a 1920×1080px screen
I'm from Costa Rica, I'm doing a Spanish translation, that's why I also know that the same behaviour is on the translations page 😅
hope it helps, please let me know if you need something else :) 
![image](https://github.com/JoeyDeVries/LearnOpenGL/assets/82833443/47aec3fa-b233-4e92-92e3-ce8069d5149d)

**Comment by JoeyDeVries** [comment]
This is perfect, thank you; I'm going to look into it. Will keep you updated!

**Comment by JoeyDeVries** [comment]
Hey, I can't seem to be able to figure out what's happening. If you're familiar with browser dev tools, would you be able to tell me the following?

- Does it happen all the time? Or only on certain pages? Or randomly?
- Name of the ad unit that's causing this (look for uppermost div parts where it says something like `<div id="waldo-tag-2246"></div>`.
- Size of the ad unit? e.g. 200x600, or 150x300. 

I'll keep debugging on my end to see if I can reproduce/figure-it-out. Sorry for the inconvenience!

**Comment by ArcE404** [comment]
Is not an inconvenience, I'm happy to help :D 

here is the HTML component of the ad:

`<div id="waldo-tag-15905" class="waldo-display-unit up-show" style="min-height: 600px;" data-google-query-id="CJ24tNW81YIDFaaj0QQd8JsCjA"></div>`

The ad is 160x600px.

![Pasted image 20231121110852](https://github.com/JoeyDeVries/LearnOpenGL/assets/82833443/a387ed4c-a156-40aa-befc-b71b24b2f3d4)

The bug constantly appears in the learnopengl.com path, the learnopengl.com/Introduction path and the translations' path. I don't see it in other places, only these.

If it helps, as you can see, the add, and its iframe component, is inside the div component with the id="nav", the same place where the list of options is located
![Pasted image 20231121110748](https://github.com/JoeyDeVries/LearnOpenGL/assets/82833443/d238b39e-ca25-4fee-a539-e9296fbd92bf)

**Comment by JoeyDeVries** [comment]
This is super helpful, thank you! It looks like an ad is overruling my default-hide behavior (unless content is large enough) which is why they're visible without positioning logic happening yet. I'm currently discussing this with my ad agency. I've pushed a hotfix for now which hopefully makes it a little less annoying, but not sure if it'll be enough. Hopefully you can at least use the menu (: 

I'll keep you posted

**Comment by ArcE404** [comment]
Thank you, for taking care and finding a solution! :)

**Comment by ArcE404** [comment]
Everything works correctly now! And yes, JS can be a mess sometimes, tell me about it. 
Thank you for resolving this issue, and thank you for all the information that is on the page, I'm really love all this stuff about graphics programming, shaders and stuff. I think I found a new passion within my passion (which is programming)

Thanks,
Augusto

**Comment by JoeyDeVries** [comment]
Of course, thanks for letting me know! And wonderful to hear ❤️ there's truly something special about creating your own graphics/stuff from nothing; enjoy the process! :D
