### ISSUE TITLE
Building on Mac OSX, issues with stb_image

### ISSUE THREAD

**Issue by SevenEightNine** [JoeyDeVries/LearnOpenGL#56]
Hello there,

I saw that this hasn't been properly tested on OSX so I thought I could help out a little bit in that department.

First I installed `glfw`, `glew`, `assimp` and `glm` through homebrew. I had to compile `SOIL` from source since I couldn't find anything on homebrew for that. Running the `CMakeLists.txt` file in this repository didn't give me any errors, but when I ran `make` I got lots of duplicate symbol errors:

```
[ 26%] Linking CXX executable bin/6.pbr/6.pbr_2.2.2.ibl_specular_textured
duplicate symbol _stbi_is_hdr_from_memory in:
    /usr/local/lib/libSOIL.a(stb_image_aug.c.o)
    libSTB_IMAGE.a(stb_image.cpp.o)
...
duplicate symbol _stbi_ldr_to_hdr_gamma in:
    /usr/local/lib/libSOIL.a(stb_image_aug.c.o)
    libSTB_IMAGE.a(stb_image.cpp.o)
ld: 20 duplicate symbols for architecture x86_64
```

I believe this is due to SOIL also including a version of `stb_image` in its binary, although I can't say for sure. I am surprised that other people have not run into this issue either.

This would be most easily fixed, I think, by simply removing `stb_image.cpp` from the sources on platforms that are affected by this. I will see if I can get this working in the `CMakeLists.txt` tomorrow, but it's hard to know if this issue will crop up on other platforms (I should be able to test it on windows, however).

**Comment by JoeyDeVries** [comment]
Yes, you are exactly right! I've included `stb_image.h` in the repository for the PBR tutorials (which had to use the latest version). Since SOIL internally uses an older version of stb_image.h we get duplicate symbol errors.

I'm currently in the process of removing both GLEW and SOIL from the repository and cleaning up all code samples (currently at Advanced OpenGL section), replacing them with GLAD and stb_image.h respectively. For now all examples should still compile (except PBR examples, unless you manually remove SOIL from their linker options), but if you wait ~a week I'll push all the changes and everything should compile perfectly again.

**Comment by SevenEightNine** [comment]
Awesome.

I have also encountered issues with the examples as GLFW requires a certain `#define` to be set, but I'll wait until you've pushed your changes before I investigate that.

**Comment by JoeyDeVries** [comment]
Alright, Thank you!
