### ISSUE TITLE
Cleaning textures samples

### ISSUE THREAD

**Issue by elect86** [JoeyDeVries/LearnOpenGL#60]
The textures examples (`transformations` also) need a quick cleaning, you can remove:

- the color values from the vbo buffer 
- the color attribute setup in the vao and fixing the stride and offset of the rest
- the vertex attribute in the shader and the passing color variable

I would have pulled, but since you are reworking the samples, I guess it's easier and faster if you do it :p

Also I am not so confident with C.. I am using Kotlin actually :)

Edit: 
- in `transformations` render loop, `glUniformMatrix4fv` shall go **after** the program binding
- in `camera_keyboard_dt`, there is no `Do_Movement()`
- in `camera_class` this is useless `float cameraSpeed = 2.5 * deltaTime;`
- add `glDeleteTextures()` in texture samples
- in `blendingSort`, `3.2.blending.vs` contains actually a fragment code

**Comment by JoeyDeVries** [comment]
I'll take a look at it, at which point I'll refine all samples when re-working the text content. This'll be a while as I'll be traveling to Japan in the upcoming weeks, but I'll leave the ticket open for then.

**Comment by elect86** [comment]
Hi Joey,

one other thing I noticed, in the ["advanced opengl"](https://github.com/JoeyDeVries/LearnOpenGL/tree/master/src/4.advanced_opengl) chapter, you jump from 3.2 to 5.1, 4 is skipped

**Comment by JoeyDeVries** [comment]
Yeah, it's because the Advanced GLSL chapter (which is chapter 4) has no source code, I decided to respect that in the numbering.

**Comment by JoeyDeVries** [comment]
I took a look at your aforementioned posts (forgot about this ticket, sorry) and they've all been fixed since the major code re-work after traveling to Japan. I haven't fixed the `glDeleteTextures()` which I might do one day, but as that's completely optional (GL cleans up the resources after execution and since we're don't care about destroying/generating textures during rendering this is fine) I'll leave it as is for now.
