### ISSUE TITLE
Why the deferred shading tutorial so painfully slow?

### ISSUE THREAD

**Issue by zlixine** [JoeyDeVries/LearnOpenGL#90]
@JoeyDeVries 

TBH, I have to admit a I have an old gpu ( GeForce 210 1 gb supports GL3 Core and DX10.1), but I compiled the deferred shading tutorial and it is painfully slow (around 9-8 FPS), I checked other tutorials (as OGLDEV) and it is very fast ( about 250 fps), I examined it with renderdoc, it seems every framebuffer call takes too much time and the renderquad function takes more time than rendering the 10 nanosuits together, why does this happen? and does this happen to you or anybody else??

**Comment by JoeyDeVries** [comment]
Yes, that makes sense. The Deferred Tutorial is meant to serve as an introduction to 'deferring' your lighting calculations to a later stage. The current approach taken in that tutorial doesn't result in any of the 'direct' performance benefits of deferred rendering (rendering light volumes for each individual light) with a high number of lights. I've made some comments on this at the end of the tutorial, wanting to write a second part to the deferred render tutorial where we discuss exactly that (but never found the time for).

**Comment by zlixine** [comment]
Actually it is too SLOW (9 fps only), is that common or just happening to me? I saw lots of your tuts based on ogldev (tuts 35, 36, 37) so I thought I could try there, I did and it is normal, also your SSAO gives me (1 fps), It happens with every tutorial you use deferred shading in it.

Just out from curiosity how fast is deferred shading tutorial on your device?

**Comment by JoeyDeVries** [comment]
The deferred tutorial being slow makes a lot of sense (as it's doing heavy loops on every fragment shader invocation). However, seeing that the SSAO tutorial is 1FPS that's weird. The most likely cause is then that your GPU is severely bandwidth-limited (as deferred shading uses several high-resolution color attachments this can quickly flood your bandwidth). SSAO can still be quite expensive by itself (play around with the settings/sample-count). You may also want to try adjusting some of the deferred color attachments to be GL_HALF_FLOAT instead of GL_FLOAT to reduce bandwidth where applicable, or even GL_UNSIGNED_BYTE at the cost of precision to see if that makes a difference. OGLDev also doesn't take full-precision position data as a color attachment, but uses the depth buffer to calculate 3D position data in the shaders itself, saving yet another color attachment (and thus bandwidth).
